### PR TITLE
added loading to wait for the query to finish

### PR DESCRIPTION
**Pull request by Lonwabo11**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259)* status: all files reviewed, 1 unresolved discussion (waiting on @Lonwabo11)

___
*[src/components/ResetPasswordForm.tsx, line 129 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259#-MO0ou_W-0wf5f1JblHO:-MO0ou_XEA6C060VwFue:byrn0ll) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/4e284b8ffdbe806222dc9369da319505b3fe4db0/src/components/ResetPasswordForm.tsx#L129)):*
> ```XML
>             );
>           }
>           if (!loading && data.passwordResetTokenStatus) {
> ```

Thanks for catching this.

It might be better to return something during loading (such as a loading indicator -- check whether any is used elsewhere by the frontend).

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/components/ResetPasswordForm.tsx, line 129 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259#-MO0ou_W-0wf5f1JblHO:-MO6bc6P7FJmoQmVe0ni:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/4e284b8ffdbe806222dc9369da319505b3fe4db0/src/components/ResetPasswordForm.tsx#L129)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks for catching this.

It might be better to return something during loading (such as a loading indicator -- check whether any is used elsewhere by the frontend).
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[src/components/ResetPasswordForm.tsx, line 132 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259#-MOVeNtX00vLXBSTafUL:-MOVeNtX00vLXBSTafUM:b-qdzi7t) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/18e2064d26f379b6f984a93793e5c233de0c3bce/src/components/ResetPasswordForm.tsx#L132)):*
> ```XML
>           }
>           if (loading) return <FontAwesomeIcon icon={faSpinner} />;
>           if (!loading && data.passwordResetTokenStatus) {
> ```

The `!loading` is unnecessary.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage and @Lonwabo11)

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/components/ResetPasswordForm.tsx, line 132 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259#-MOVeNtX00vLXBSTafUL:-MOWGTTwEat73vuemQEt:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/18e2064d26f379b6f984a93793e5c233de0c3bce/src/components/ResetPasswordForm.tsx#L132)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The `!loading` is unnecessary.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/259)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
