### PR TITLE
Fly download

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251)* status: 4 of 33 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/query/parse.ts, line 389 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251#-MFVg5W_ygWKbPKnzV-o-r1-389:-MGmgblS7Ernre9aGbcV:b-qd7t5w) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/8bd5dfc3b1d1ad9b68f2d6fbefd86a3e5b1610c3/src/util/query/parse.ts#L389)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should explain why you use "as any" (and, further down, why you use ts-ignore). Assuming the two fix thbe same, you should choose one version and stick to it. :)
</blockquote></details>

what was the exact reason.

I know isNumber str | number of which it should be a boolean.
but where the never is coming from?

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251)* status: 4 of 33 files reviewed, 1 unresolved discussion (waiting on @ts-ignore)

___
*[src/util/query/parse.ts, line 389 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251#-MFVg5W_ygWKbPKnzV-o-r1-389:-MGmiMsN5ShRtTr-AAw8:bi1kcqx) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/8bd5dfc3b1d1ad9b68f2d6fbefd86a3e5b1610c3/src/util/query/parse.ts#L389)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

what was the exact reason.

I know isNumber str | number of which it should be a boolean.
but where the never is coming from?

</blockquote></details>

The problem was caused by the type definition for isNumber. But it seems my PR in this regard has made its way to npm. So maybe you can try to update @types/is-number and see whether the code then works without the workaround and the @ts-ignore comments?

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251)* status: 5 of 33 files reviewed, 1 unresolved discussion (waiting on @ts-ignore)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251)* status: 3 of 33 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero, @hettlage, and @ts-ignore)

___
*[src/util/query/parse.ts, line 389 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251#-MFVg5W_ygWKbPKnzV-o-r1-389:-MGrAOWu6mmPRLbx2UKp:b-fdp7e7) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/8bd5dfc3b1d1ad9b68f2d6fbefd86a3e5b1610c3/src/util/query/parse.ts#L389)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The problem was caused by the type definition for isNumber. But it seems my PR in this regard has made its way to npm. So maybe you can try to update @types/is-number and see whether the code then works without the workaround and the @ts-ignore comments?
</blockquote></details>

DONE.
I didn't understand what ` @ts-ignore comments` about till I searched for it.
I added the to test that my code is working and commit then that you can see my problem just like that they were gone and they were not neccesarry after adding `as any`.
but done now.

**Review by hettlage — COMMENTED** [review]
> Reviewed 26 of 32 files at r1, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251)* status: all files reviewed, 1 unresolved discussion (waiting on @ts-ignore)

**Review by hettlage — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/251#-:-MIrYI-Q8ABZ68wH2sFa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
