### PR TITLE
Search results as csv

### LINKED ISSUE #263: Add option to download search results as csv file

### PR DESCRIPTION
**Pull request by Lonwabo11**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266)* status: all files reviewed, 10 unresolved discussions (waiting on @Lonwabo11)

*[a discussion](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2n_MW-0c_XccJyHsh:-MS2n_MW-0c_XccJyHsi:b-z3ejde) (no related file):*
react-csv and @types/react-csv seem to be missing in the package.json file.

The csv file should not include a Preview column.

---
___
*[src/components/searchFormComponents/SearchPage.tsx, line 111 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2pF2xCOdTeIXDGLXt:-MS2pF2xCOdTeIXDGLXu:bf9ofll) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L111)):*
> ```XML
> `;
> 
> export function download(columns: any[], SearchResults: any) {
> ```

You should use the correct types rather than any wherever reasonably possible

Variable names should not start with a capital.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 112 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2zzjN3VAaTo4WTxdv:-MS2zzjN3VAaTo4WTxdw:b-rzq9f0) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L112)):*
> ```XML
> 
> export function download(columns: any[], SearchResults: any) {
>   const tableHeaderContent: ISearchResultsTableColumn[] = [];
> ```

Maybe "includedColumns" rather than "tableHeaderContent"?
___
*[src/components/searchFormComponents/SearchPage.tsx, line 124 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2wiM28YNJYp5sYALc:-MS2wiM28YNJYp5sYALd:bo62wl2) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L124)):*
> ```XML
>   }
>   SearchResults.forEach((result: any) => {
>     result.files.forEach((artifact: any) => {
> ```

"file" would be better than "artifact".
___
*[src/components/searchFormComponents/SearchPage.tsx, line 127 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2tTjo1N0XpcjC6VzM:-MS2tTjo1N0XpcjC6VzN:bo9myqz) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L127)):*
> ```XML
>       const finalObj: any = {};
>       tableHeaderContent.map((header) => {
>         if (
> ```

The column headers have a format method, and it probably would be better to use it.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 135 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2yoQ8D9YxtqCvrLLV:-MS2yoQ8D9YxtqCvrLLW:bbprn0) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L135)):*
> ```XML
>             isNumeric(artifact[header.dataKey])
>           ) {
>             finalObj[header.name.toLowerCase()] = parseFloat(
> ```

Is there a need for the lower case?
___
*[src/components/searchFormComponents/SearchPage.tsx, line 162 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS3-8ey2vuoSPlCko9o:-MS3-8ey2vuoSPlCko9p:bfsbsqi) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L162)):*
> ```XML
>   });
> 
>   tableHeaderContent.forEach((header) => {
> ```

Probably better "column" than "header".
___
*[src/components/searchFormComponents/SearchPage.tsx, line 164 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2z52gEpAh1eDmACel:-MS2z52gEpAh1eDmACem:bl2t6jt) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L164)):*
> ```XML
>   tableHeaderContent.forEach((header) => {
>     const finalHeaders: any = {};
>     if (header.name === "Info") {
> ```

Couldn't you filter this out at the beginning of the function, as you do for "dummy'? Also, the delete doesn't do anything, as finalHeaders is an empty object.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 169 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS3-lt1A0am8IGXqLjS:-MS3-lt24C5TJEKGps_M:bhmjenq) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L169)):*
> ```XML
>       finalHeaders.label = header.name;
>       finalHeaders.key = header.name.toLowerCase();
>       csvHeaders.push(finalHeaders);
> ```

Simpler (no need for finalHeaders):

```
csvHeaders.push({ label: header.name, key: header.name.toLowerCase() }(
```
___
*[src/components/searchFormComponents/SearchPage.tsx, line 324 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS30KBk9n23-WTKMvr7:-MS30KBk9n23-WTKMvr8:buduyjp) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L324)):*
> ```XML
>                           style={{ marginLeft: 75 }}
>                         >
>                           Download results as CSV
> ```

Should be centered.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2n_MW-0c_XccJyHsh:-MS6mvvL6xo_dBmfJxC1:by5o9n3) (no related file):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

react-csv and @types/react-csv seem to be missing in the package.json file.

The csv file should not include a Preview column.
</blockquote></details>

forgot to push the changes in package.json and yarn.lock. I  will remove preview as well 

---
___
*[src/components/searchFormComponents/SearchPage.tsx, line 111 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2pF2xCOdTeIXDGLXt:-MS7QCCj3PopDMZM6VVW:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L111)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should use the correct types rather than any wherever reasonably possible

Variable names should not start with a capital.
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 112 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2zzjN3VAaTo4WTxdv:-MS6tZyA9hssF58YuMYx:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L112)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe "includedColumns" rather than "tableHeaderContent"?
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 124 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2wiM28YNJYp5sYALc:-MS6z01NAS5Zg0mFvvuf:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"file" would be better than "artifact".
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 127 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2tTjo1N0XpcjC6VzM:-MS7MWId436gkNG73NTv:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L127)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The column headers have a format method, and it probably would be better to use it.
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 135 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2yoQ8D9YxtqCvrLLV:-MS7D4OE67nhN4B1oSXl:bxinm3c) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L135)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is there a need for the lower case?
</blockquote></details>

I was trying something and totally forgot to remove it. It works even without the lower case.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 162 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS3-8ey2vuoSPlCko9o:-MS7DlsL9TnYNqUsr6np:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Probably better "column" than "header".
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 164 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2z52gEpAh1eDmACel:-MS7Khtx8okYkWSgdWyk:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L164)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Couldn't you filter this out at the beginning of the function, as you do for "dummy'? Also, the delete doesn't do anything, as finalHeaders is an empty object.
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 169 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS3-lt1A0am8IGXqLjS:-MS7KjF56RjIx00Ayavh:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L169)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Simpler (no need for finalHeaders):

```
csvHeaders.push({ label: header.name, key: header.name.toLowerCase() }(
```
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 324 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS30KBk9n23-WTKMvr7:-MS7bduZ8JtRbIpOIer5:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L324)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be centered.
</blockquote></details>

Done.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2n_MW-0c_XccJyHsh:-MS7cMK5EZK0okTzMDJU:b-896fix) (no related file):*
<details><summary><i>Previously, Lonwabo11 (Lonwabo Zaula) wrote…</i></summary><blockquote>

forgot to push the changes in package.json and yarn.lock. I  will remove preview as well 
</blockquote></details>

Done.

---

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[package.json, line 37 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MSDmbhIDsI2dLaYYQBR:-MSDmbhIDsI2dLaYYQBS:b62ya3b) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/0c9c76b2ffb9f9fdf3f2501c1056f8be3fb33365/package.json#L37)):*
> ```JSON
>     "bulma-badge": "^3.0.1",
>     "bulma-extensions": "^6.2.7",
>     "csv-writer": "^1.6.0",
> ```

Do you need to explicitly add this to the package.json file?
___
*[src/components/searchFormComponents/SearchPage.tsx, line 111 at r1](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MS2pF2xCOdTeIXDGLXt:-MSDxBi00V5ouSHqlWT_:b6f2gpw) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/d183c8bf60f15a54ad7dbcfe241cd2f4739eb85a/src/components/searchFormComponents/SearchPage.tsx#L111)):*
<details><summary><i>Previously, Lonwabo11 (Lonwabo Zaula) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Uhm, they should _not_ start with a capital... :-)
___
*[src/components/searchFormComponents/SearchPage.tsx, line 110 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MSDn1hY97DbWtsUVbTd:-MSDn1hY97DbWtsUVbTe:b-m0xdmz) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/0c9c76b2ffb9f9fdf3f2501c1056f8be3fb33365/src/components/searchFormComponents/SearchPage.tsx#L110)):*
> ```XML
> `;
> 
> export function Download(Columns: any[], SearchResults: any) {
> ```

Function and variable names shouldn't start with an upper case letter.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 111 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MSDwUvs6IQJdEuadeVu:-MSDwUvs6IQJdEuadeVv:b-vids3n) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/0c9c76b2ffb9f9fdf3f2501c1056f8be3fb33365/src/components/searchFormComponents/SearchPage.tsx#L111)):*
> ```XML
> 
> export function Download(Columns: any[], SearchResults: any) {
>   const IncludedColumns: ISearchResultsTableColumn[] = [];
> ```

We should have a chat about this part...
___
*[src/components/searchFormComponents/SearchPage.tsx, line 126 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MSDqZeu4pByA0QbPTgK:-MSDqZeu4pByA0QbPTgL:b-vzae1t) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/0c9c76b2ffb9f9fdf3f2501c1056f8be3fb33365/src/components/searchFormComponents/SearchPage.tsx#L126)):*
> ```XML
>     result.files.forEach((file: any) => {
>       const FinalObj: any = {};
>       IncludedColumns.map((header) => {
> ```

It seems that the condition `!(header.name in FinalObj)` and the inner `if`, as well as

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[package.json, line 37 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MSDmbhIDsI2dLaYYQBR:-MSS3wMy2yrAt7-Xk788:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/0c9c76b2ffb9f9fdf3f2501c1056f8be3fb33365/package.json#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you need to explicitly add this to the package.json file?
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 110 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MSDn1hY97DbWtsUVbTd:-MSRZnfp0pQEjzNeqtTh:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/0c9c76b2ffb9f9fdf3f2501c1056f8be3fb33365/src/components/searchFormComponents/SearchPage.tsx#L110)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Function and variable names shouldn't start with an upper case letter.
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 111 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MSDwUvs6IQJdEuadeVu:-MSS1VqX15u9yAsnzIPI:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/0c9c76b2ffb9f9fdf3f2501c1056f8be3fb33365/src/components/searchFormComponents/SearchPage.tsx#L111)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We should have a chat about this part...
</blockquote></details>

Done.
___
*[src/components/searchFormComponents/SearchPage.tsx, line 126 at r2](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266#-MSDqZeu4pByA0QbPTgK:-MSS1Uyk8070my5sje1v:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-frontend/blob/0c9c76b2ffb9f9fdf3f2501c1056f8be3fb33365/src/components/searchFormComponents/SearchPage.tsx#L126)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems that the condition `!(header.name in FinalObj)` and the inner `if`, as well as 
</blockquote></details>

Done.

**Review by Lonwabo11 — COMMENTED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266)* status: 5 of 8 files reviewed, 6 unresolved discussions (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-frontend/266)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
